name: Deploy Workflow - deploy to server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Copy files via SCP
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          local: "."
          remote: "./test2"
          # pre_upload: rm -r /var/www/html/*
          post_upload: echo "This will be executed after the upload!"
          ssh_options: -o StrictHostKeyChecking=no # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v
