name: Deploy Workflow - deploy to server

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Copy files via SCP
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          local: "."
          remote: "./wrinkle.dk"
          pre_upload: rm -rf ./wrinkle.dk && mkdir wrinkle.dk && rm-rf /var/www/wrinkle.dk
          post_upload: cd wrinkle.dk && ls && npm install && npm run build && scp -r build/* /var/www/wrinkle.dk && echo "copied I guess ..."
          # post_upload: cd test && ls && npm install && npm run build && pm2 stop bingo && pm2 start server.js --name "bingo"
          ssh_options: -o StrictHostKeyChecking=no # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v
