name: Deploy Workflow - deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Copy files via SCP
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          local: "."
          remote: "./wrinkle.dk"
          pre_upload: rm -rf ./wrinkle.dk && mkdir wrinkle.dk && rm -rf /var/www/wrinkle.dk && mkdir /var/www/wrinkle.dk && mkdir /var/www/wrinkle.dk/build
          post_upload: cd wrinkle.dk && ls && npm install && npm run build && scp -r build/* /var/www/wrinkle.dk/build && echo "copy to server complete"
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -v
