name: Dev Workflow - linting and testing

on:
  push:
    branches:
      - test-actions

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: this step will use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install dependencies with a clean slate
        run: npm ci
      - name: run the code linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install dependencies with a clean slate
        run: npm ci
      - name: run the unit tests
        run: npm run test
