name: Peanuts
on: [push]
jobs:
  Test-Job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v3
      - name: List files
        run: |
          ls ${{ github.workspace }}
      - run: echo "this job's status is ${{ job.status }} ..."
